# Generated by Django 3.2.9 on 2021-11-16 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_title', models.CharField(max_length=250, verbose_name='Название курса:')),
                ('course_text', models.TextField(max_length=500, verbose_name='Краткое описание курса:')),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации курса:')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='Автор коментария:')),
                ('comment_text', models.TextField(max_length=500, verbose_name='Текст комментария:')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.course')),
            ],
        ),
    ]
